version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: security-vault
      SPRING_DATASOURCE_URL: jdbc:postgresql://ep-wild-truth-a5ncxzy2.us-east-2.aws.neon.tech/securevault-db
      SPRING_DATASOURCE_USERNAME: tododb_owner
      SPRING_DATASOURCE_PASSWORD: oydwhK9V1nFX
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver

        #postgres:
    #container_name: securevault-api
      #image: postgres
      #environment:
      #POSTGRES_DB: securevault
        #POSTGRES_USER: admin
        #POSTGRES_PASSWORD: 123456
        #ports:
           #      - 5432:5432 
