version: '3.8'

services:
  postgres:
    container_name: securevault-api
    image: postgres
    environment:
      POSTGRES_DB: securevault
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432