version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: security-vault
      SPRING_DATASOURCE_URL: jdbc:postgresql://admin:123456@localhost:5432/securevault-db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver

  postgres:
    container_name: securevault-api
      image: postgres
    environment:
        POSTGRES_DB: securevault
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: 123456
        ports:
           - 5432:5432 
